<?php
/**
 * @file
 * jdt_user_notes module .module file
 */

/**
 * Implements hook_menu().
 */
function jdt_user_notes_menu() {
  $items['node/%node/addnote'] = array(
    'title' => 'Add note',
    'description' => 'Add note.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('jdt_user_notes_add_note_form', 1),
    'access callback' => 'jdt_user_notes_add_note_access_callback',
    'access arguments' => array(1),
    'file' => 'jdt_user_notes.admin.inc',
  );
  $items['note/%jdt_user_notes_note/edit'] = array(
    'title' => 'Edit notes',
    'description' => 'Edit notes.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('jdt_user_notes_edit_note_form', 1),
    'access callback' => 'jdt_user_notes_edit_note_access_callback',
    'access arguments' => array(1),
    'file' => 'jdt_user_notes.admin.inc',
  );

  return $items;
}

/**
 * Loads the note object.
 */
function jdt_user_notes_note_load($note_id) {
  $result = db_select('jdt_user_notes_article_notes', 'jun')
    ->fields('jun')
    ->condition('note_id', $note_id)
    ->execute()
    ->fetchObject();
  return $result;
}

/**
 * Access callback function to add note to article.
 */
function jdt_user_notes_add_note_access_callback($node) {
  global $user;
  return $node->type == 'article2' && (in_array('administrator', $user->roles) || user_access('add note'));
}

/**
 * Access callback function to edit a note.
 */
function jdt_user_notes_edit_note_access_callback($note) {
  global $user;
  return in_array('administrator', $user->roles) || ($user->uid == $note->author_uid && user_access('edit note'));
}

/**
 * Implements hook_permission().
 */
function jdt_user_notes_permission() {
  return array(
    'add note' => array(
      'title' => t('Add note'),
      'description' => t('Add notes to articles'),
    ),
    'edit note' => array(
      'title' => t('Edit note'),
      'description' => t('Edit notes on articles'),
      'restrict access' => TRUE,
    ),
    'delete note' => array(
      'title' => t('Delete note'),
      'description' => t('Delete notes from articles'),
      'restrict access' => TRUE,
    ),
  );
}
