<?php


/**
 * Implements hook_update_N.
 */


function central_update_7001() {
	$module_list = array("views", 
		"features", 
		"strongarm", 
		"context", 
		"pathauto", 
		"diff", 
		"libraries", 
		"jquery_update", "devel", "module_filter", "admin_menu", "jdt_content_type_article");
	module_enable($module_list);
	
	return t('Central module is updated.');
}

function central_update_7002() {
	module_enable(array("jdt_content_type_article"));
}